services:
  icloud-hme-gen:
    build: .
    container_name: icloud-hme-gen
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - MODE=generate
      - AMOUNT=5
      - ALLOW_DOT=y
    volumes:
      - ./cookies.json:/app/cookies.json
      - ./emails.txt:/app/emails.txt
    restart: unless-stopped
